default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: a1234
  host: localhost

development:
  <<: *default
  database: crypto_exchanger_development

test:
  <<: *default
  database: crypto_exchanger_test

production:
  <<: *default
  database: crypto_exchanger_production
  username: crypto_exchanger
  password: <%= ENV['DATABASE_PASSWORD'] %>